---
sidebar: sidebar 
permalink: reference-configs-aws.html 
keywords: ec2, instance, type, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations, sizes, disks, networking, bandwidth, professional package 
summary: Várias configurações do Cloud Volumes ONTAP são suportadas na AWS. 
---
= Configurações com suporte para Cloud Volumes ONTAP na AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Várias configurações do Cloud Volumes ONTAP são suportadas na AWS.



== Número de nós suportados

O Cloud Volumes ONTAP está disponível na AWS como um sistema de nó único e como um par de nós de alta disponibilidade (HA) para tolerância a falhas e operações ininterruptas.

Não há suporte para atualizar um sistema de nó único para um par HA.  Se você quiser alternar entre um sistema de nó único e um par de HA, precisará implantar um novo sistema e replicar os dados do sistema existente para o novo sistema.



== Armazenamento suportado

O Cloud Volumes ONTAP oferece suporte a vários tipos de discos EBS e armazenamento de objetos S3 para camadas de dados.  A capacidade máxima de armazenamento é determinada pela licença que você escolher.



=== Suporte de armazenamento por licença

Cada licença suporta uma capacidade máxima de sistema diferente. A capacidade máxima do sistema inclui armazenamento baseado em disco, além de armazenamento de objetos usado para armazenamento de dados em camadas.  A NetApp não oferece suporte para exceder esse limite.

[role="tabbed-block"]
====
.Licenças baseadas em capacidade
--
[cols="h,d,d"]
|===
|  | Freemium | Licença baseada em capacidade 


 a| 
*Capacidade máxima do sistema* (discos + armazenamento de objetos) ^1^
| 500 GiB | Flexível ^2^ 


 a| 
*Tipos de disco suportados*
 a| 
* SSD de uso geral (gp3 e gp2) ^3^,^5^
* SSD IOPS provisionado (io1) ^3^
* HDD otimizado para throughput (st1) ^4^




 a| 
*Escalonamento de dados frios para S3*
 a| 
Suportado

|===
Observações:

. Para um par HA, o limite de capacidade é para todo o par HA.  Não é por nó.  Por exemplo, se você usar a licença Premium, poderá ter até 368 TiB de capacidade entre os dois nós.
. Para algumas configurações, os limites de disco impedem que você atinja o limite de capacidade usando apenas discos.  Nesses casos, você pode atingir o limite de capacidade por https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["hierarquização de dados inativos para armazenamento de objetos"^] .  Para obter informações sobre limites de disco, consultelink:reference-limits-aws.html["limites de armazenamento"] .
+
Com o licenciamento baseado em capacidade, cada sistema Cloud Volumes ONTAP oferece suporte à hierarquização para armazenamento de objetos. A capacidade total em camadas pode ser ampliada até o limite de bucket do provedor de nuvem. Embora a licença não imponha restrições de capacidade, você deve seguir as https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Melhores práticas do FabricPool"^] para garantir desempenho ideal, confiabilidade e eficiência de custos ao configurar e gerenciar camadas.

. O desempenho de gravação aprimorado é habilitado ao usar SSDs com todas as configurações do Cloud Volumes ONTAP .
. Não é recomendado hierarquizar dados para armazenamento de objetos ao usar HDDs com taxa de transferência otimizada (st1).
. As configurações do Cloud Volumes ONTAP nas zonas locais da AWS oferecem suporte apenas ao tipo de disco SSD de uso geral (gp2).  Nenhum outro tipo de disco é suportado no Cloud Volumes ONTAP nas Zonas Locais da AWS.


--
.Licenças baseadas em nós
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explore | Padrão PAYGO | PAYGO Premium | BYOL baseado em nó 


| Capacidade máxima do sistema (discos + armazenamento de objetos) | 2 TiB | 10 TiB | 368 TiB ^2^ | 368 TiB por licença ^2^ 


| Tipos de disco suportados  a| 
* SSD de uso geral (gp3 e gp2) ^3^,^5^
* SSD IOPS provisionado (io1) ^3^
* HDD otimizado para throughput (st1) ^4^




| Camada de dados frios para S3 | Não suportado 3+| Suportado 
|===
Observações:

. Para um par HA, o limite de capacidade é para todo o par HA.  Não é por nó.  Por exemplo, se você usar a licença Premium, poderá ter até 368 TiB de capacidade entre os dois nós.
. Para algumas configurações, os limites de disco impedem que você atinja o limite de capacidade usando apenas discos.  Nesses casos, você pode atingir o limite de capacidade por https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["hierarquização de dados inativos para armazenamento de objetos"^] .  Para obter informações sobre limites de disco, consultelink:reference-limits-aws.html["limites de armazenamento"] .
. O desempenho de gravação aprimorado é habilitado ao usar SSDs com todas as configurações do Cloud Volumes ONTAP , exceto o PAYGO Explore.
. Não é recomendado hierarquizar dados para armazenamento de objetos ao usar HDDs com taxa de transferência otimizada (st1).
. As configurações do Cloud Volumes ONTAP nas zonas locais da AWS oferecem suporte apenas ao tipo de disco SSD de uso geral (gp2).


--
====


=== Tamanhos de disco suportados

Na AWS, um agregado pode conter até 6 discos, todos do mesmo tamanho.  Mas se você tiver uma configuração compatível com o recurso Amazon EBS Elastic Volumes, um agregado poderá conter até 8 discos. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["Saiba mais sobre o suporte para Elastic Volumes"^]

[cols="3*"]
|===
| SSDs de uso geral (gp3 e gp2) | SSDs IOPS provisionados (io1) | HDDs com taxa de transferência otimizada (st1) 


 a| 
* 100 GiB
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB

 a| 
* 100 GiB
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB

 a| 
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB


|===


== Computação EC2 suportada

Cada licença do Cloud Volumes ONTAP oferece suporte a diferentes tipos de instâncias do EC2.  Para sua conveniência, a tabela abaixo mostra a vCPU, a RAM e a largura de banda para cada tipo de instância suportada. https://aws.amazon.com/ec2/instance-types/["Você deve consultar a AWS para obter os detalhes mais recentes e completos sobre os tipos de instância do EC2"^] .

O Cloud Volumes ONTAP pode ser executado em uma instância EC2 reservada ou sob demanda.  Soluções que usam outros tipos de instância não são suportadas.

As larguras de banda mostradas na tabela abaixo correspondem aos limites documentados da AWS para cada tipo de instância.  Esses limites não estão totalmente alinhados com o que o Cloud Volumes ONTAP pode oferecer.  Para o desempenho esperado, consulte https://www.netapp.com/pdf.html?item=/media/9088-tr4383pdf.pdf["Relatório Técnico NetApp 4383: Caracterização de Desempenho de Cloud Volumes ONTAP na Amazon Web Services com Cargas de Trabalho de Aplicativos"^] .

[cols="8*"]
|===
| Licença | Instância suportada | vCPU | BATER | Cache Flash ^1^ | Largura de banda da rede (Gbps) | Largura de banda EBS (Mbps) | Alta velocidade de gravação ^2^ 


| *Explore ou qualquer outra licença* | m5.xlarge ^6^ | 4 | 16 | Não suportado | Até 10 | Até 4.750 | Suportado (somente nó único) 


.3+| *Licença padrão ou qualquer outra* | r5.xlarge ^6^ | 4 | 32 | Não suportado | Até 10 | Até 4.750 | Suportado (somente nó único) 


| m5a.2xlarge | 8 | 32 | Não suportado | Até 10 | Até 2.880 | Suportado 


| m5.2xgrande ^6^ | 8 | 32 | Não suportado | Até 10 | Até 4.750 | Suportado 


.22+| *Licença Premium ou qualquer outra* | m5n.2xlarge | 8 | 32 | Não suportado | Até 25 | Até 4.750 | Suportado 


| r5.2xgrande ^6^ | 8 | 64 | Não suportado | Até 10 | Até 4.750 | Suportado 


| r5d.2xlarge | 8 | 64 | Suportado | Até 10 | Até 4.750 | Suportado 


| c5d.4xgrande ^6^ | 16 | 32 | Suportado | Até 10 | 4.570 | Suportado 


| m5.4xgrande ^6^ | 16 | 64 | Não suportado | Até 10 | 4.750 | Suportado 


| m5dn.4xlarge | 16 | 64 | Suportado | Até 25 | 4.750 | Suportado 


| m5d.8xlarge | 32 | 128 | Suportado | 10 | 6.800 | Suportado 


| r5.8xlarge | 32 | 256 | Não suportado | 10 | 6.800 | Suportado 


| c5.9xlarge | 36 | 72 | Não suportado | 10 | 9.500 | Suportado 


| c5d.9xlarge | 36 | 72 | Suportado | 10 | 9.500 | Suportado 


| c5n.9xlarge | 36 | 96 | Não suportado | 50 | 9.500 | Suportado 


| c5a.12xlarge | 48 | 96 | Não suportado | 12 | 4.750 | Suportado 


| c5.18xlarge | 64 ^4^ | 144 | Não suportado | 25 | 19.000 | Suportado 


| c5d.18xlarge | 64 ^4^ | 144 | Suportado | 25 | 19.000 | Suportado 


| m5d.12xlarge | 48 | 192 | Suportado | 12 | 9.500 | Suportado 


| m5dn.12xlarge | 48 | 192 | Suportado | 50 | 9.500 | Suportado 


| c5n.18xlarge | 64 ^4^ | 192 | Não suportado | 100 | 19.000 | Suportado 


| m5a.16xlarge | 64 | 256 | Não suportado | 12 | 9.500 | Suportado 


| m5.16xlarge | 64 | 256 | Não suportado | 20 | 13.600 | Suportado 


| r5.12xgrande ^3^ | 48 | 384 | Não suportado | 10 | 9.500 | Suportado 


| m5dn.24xlarge | 64 ^4^ | 384 | Suportado | 100 | 19.000 | Suportado 


| m6id.32xlarge | 64 ^4^ | 512 | Suportado | 50 | 40.000 | Suportado 
|===
. Alguns tipos de instância incluem armazenamento NVMe local, que o Cloud Volumes ONTAP usa como _Flash Cache_.  O Flash Cache acelera o acesso aos dados por meio do cache inteligente em tempo real de dados de usuários lidos recentemente e metadados do NetApp .  É eficaz para cargas de trabalho aleatórias com uso intensivo de leitura, incluindo bancos de dados, e-mail e serviços de arquivo.  A compactação deve ser desabilitada em todos os volumes para aproveitar as melhorias de desempenho do Flash Cache. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["Saiba mais sobre Flash Cache"^] .
. O Cloud Volumes ONTAP oferece suporte a alta velocidade de gravação com a maioria dos tipos de instância ao usar um par de HA.  Alta velocidade de gravação é suportada com todos os tipos de instância ao usar um único sistema de nó. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["Saiba mais sobre como escolher uma velocidade de gravação"^] .
. O tipo de instância r5.12xlarge tem uma limitação conhecida de suporte.  Se um nó for reinicializado inesperadamente devido a um pânico, o sistema pode não coletar os arquivos principais usados para solucionar problemas e identificar a causa raiz deles.  O cliente aceita os riscos e os termos de suporte limitados e assume toda a responsabilidade de suporte caso essa condição ocorra.  Essa limitação afeta pares de HA recém-implantados e pares de HA atualizados da versão 9.8.  A limitação não afeta sistemas de nó único recém-implantados.
. Embora esses tipos de instância do EC2 suportem mais de 64 vCPUs, o Cloud Volumes ONTAP suporta apenas até 64 vCPUs.
. Ao escolher um tipo de instância EC2, você pode especificar se é uma instância compartilhada ou dedicada.
. As zonas locais da AWS são suportadas nas seguintes famílias de tipos de instância do EC2 com tamanhos de xgrande a 4xgrande: M5, C5, C5d, R5 e R5d. link:https://aws.amazon.com/about-aws/global-infrastructure/localzones/features/?nc=sn&loc=2["Você deve consultar a AWS para obter os detalhes mais recentes e completos sobre os tipos de instâncias EC2 com suporte em Zonas Locais"^] .
+
Alta velocidade de gravação não é suportada com esses tipos de instância nas Zonas Locais da AWS.





=== Instâncias c4, m4 e r4 não são mais suportadas

O Cloud Volumes ONTAP não oferece mais suporte aos tipos de instância EC2 c4, m4 e r4 na AWS.  Se o seu sistema for executado em uma instância c4, m4 ou r4, mude para uma instância c5, m5 ou r5.  Você não pode atualizar para esta versão até alterar o tipo de instância.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Aprenda como alterar o tipo de instância EC2 para o Cloud Volumes ONTAP"^] .

Para mais informações, consulte:

* https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Converting_an_AWS_Xen_CVO_instance_to_Nitro_KVM["Artigo da base de conhecimento (KB): Convertendo uma instância AWS Xen CVO para Nitro KVM"^]
* https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Unable_to_change_the_instance_type_from_r4_to_r5_with_disk_count_error["Artigo da KB: Não é possível alterar o tipo de instância de r4 para r5 com erro de contagem de disco"^]
* link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Saiba mais sobre o fim da disponibilidade e do suporte para esses tipos de instância"^]




== Regiões suportadas

Para suporte regional da AWS, consulte https://bluexp.netapp.com/cloud-volumes-global-regions["Regiões globais da Cloud Volumes"^] .
