---
sidebar: sidebar 
permalink: reference-provider-integrations.html 
keywords: maintenance event, azure maintenance event, cloud provider, issues, support, SMB CA in CVO 
summary: Esta página descreve como a NetApp trabalha com provedores de nuvem para resolver problemas que possam surgir. 
---
= Colaboração com provedores de nuvem para Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Saiba como a NetApp colabora com provedores de nuvem para resolver possíveis problemas.



== Melhores práticas de suporte colaborativo

A NetApp está comprometida em fornecer suporte ao Licenciado e usará esforços comercialmente razoáveis ​​para resolver problemas de suporte técnico do Cloud Volumes ONTAP quando relatados pelo Licenciado.  A NetApp e o provedor de nuvem aplicável não têm nenhuma obrigação direta de suporte ao software ou infraestrutura licenciados um do outro.

A NetApp implementou ferramentas destinadas a conectar-se com provedores de nuvem aplicáveis ​​em questões técnicas do cliente que podem ser resultado dos serviços do provedor de nuvem aplicável.  No entanto, a melhor maneira de manter um fluxo de suporte contínuo é que os clientes (i) mantenham um contrato de suporte atual com a NetApp e o provedor de nuvem aplicável e (ii) coordenem reuniões conjuntas de escalonamento com a NetApp e o provedor de nuvem aplicável quando surgirem problemas técnicos e o cliente precisar de clareza sobre quais produtos ou serviços estão causando esses problemas técnicos.



== Eventos de manutenção do Azure

A Microsoft agenda e anuncia programaticamente eventos de manutenção em sua infraestrutura de máquina virtual (VM) do Azure que podem afetar as VMs do Cloud Volumes ONTAP .  Esses eventos são anunciados 15 minutos antes da janela de manutenção.

O tratamento especial de eventos de manutenção é suportado para pares de alta disponibilidade (HA) do Cloud Volumes ONTAP .  Para manter a integridade do aplicativo, realizamos uma aquisição preventiva para priorizar a estabilidade, pois qualquer perda de conectividade de mais de 15 segundos desabilitará os recursos de failover.

Quando a janela de manutenção for anunciada, o nó parceiro do nó alvo realizará uma aquisição.  Quando a manutenção estiver concluída, uma devolução será iniciada.  Após a devolução, espera-se que o par HA retorne a um estado saudável.  Se isso não ocorrer, entre em contato com o Suporte da NetApp para obter assistência.  Observe que os eventos de manutenção são direcionados a uma das VMs em um par de HA por vez e, normalmente, ambos os nós são direcionados em um período de tempo relativamente curto.

Clientes CIFS/SMB que utilizam compartilhamentos CIFS não continuamente disponíveis do Cloud Volumes ONTAP sofrerão perda de sessão tanto quando ocorrer uma aquisição quanto quando o agregado que a sessão está usando for devolvido ao nó inicial do agregado. Essa é uma limitação imposta pelo próprio protocolo CIFS/SMB. Você pode usar produtos de terceiros aprovados para evitar problemas decorrentes de aquisição e devolução. Para obter mais assistência, entre em contato com o Suporte da NetApp .


NOTE: https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["Ações SMB continuamente disponíveis"^] para operações não disruptivas não são suportadas no Cloud Volumes ONTAP.
