---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: O Cloud Volumes ONTAP 9.16.1 inclui um novo aprimoramento. 
---
= Novidades no Cloud Volumes ONTAP 9.16.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Cloud Volumes ONTAP 9.16.1 inclui novos aprimoramentos.

Recursos e aprimoramentos adicionais também são introduzidos nas versões mais recentes do NetApp Console. Veja o https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Notas de versão do Cloud Volumes ONTAP"^] para mais detalhes.



== 9.16.1 P8 (16 de outubro de 2025)

O patch Cloud Volumes ONTAP 9.16.1 P8 já está disponível para atualização no Azure e no Google Cloud. No entanto, esta versão não está disponível para atualização na AWS. O Console solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P8["Veja a lista de bugs corrigidos no patch P8"^](É necessário fazer login no site de suporte da NetApp ).



== 9.16.1 P7 (09 de outubro de 2025)

O patch Cloud Volumes ONTAP 9.16.1 P7 já está disponível para atualização no Azure e no Google Cloud. No entanto, esta versão não está disponível para atualização na AWS. O Console solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P7["Veja a lista de bugs corrigidos no patch P7"^] (É necessário fazer login no site de suporte da NetApp ).



== 9.16.1 P6 (09 de outubro de 2025)

O patch Cloud Volumes ONTAP 9.16.1 P6 já está disponível para atualização no Azure e no Google Cloud. No entanto, esta versão não está disponível para atualização na AWS. O Console solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P6["Veja a lista de bugs corrigidos no patch P6"^] (É necessário fazer login no site de suporte da NetApp ).



== 9.16.1 P5 (28 de julho de 2025)

O patch Cloud Volumes ONTAP 9.16.1 P5 já está disponível para atualização no Azure e no Google Cloud.  No entanto, esta versão não está disponível para atualização na AWS. O BlueXP solicitará que você atualize seus sistemas existentes para esta versão do patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P5["Veja a lista de bugs corrigidos no patch P5"^] (É necessário fazer login no site de suporte da NetApp ).



== 9.16.1 P4 (08 de julho de 2025)

O patch Cloud Volumes ONTAP 9.16.1 P4 já está disponível para atualização no Azure e no Google Cloud.  No entanto, esta versão não está disponível para atualização na AWS. O BlueXP solicitará que você atualize seus sistemas existentes para esta versão do patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P4["Veja a lista de bugs corrigidos no patch P4"^] (É necessário fazer login no site de suporte da NetApp ).



== 9.16.1 P3 (29 de maio de 2025)

O patch Cloud Volumes ONTAP 9.16.1 P3 já está disponível para atualização no Azure e no Google Cloud.  No entanto, esta versão não está disponível para atualização na AWS. O BlueXP solicitará que você atualize seus sistemas existentes para esta versão do patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P3["Veja a lista de bugs corrigidos no patch P3"^] (É necessário fazer login no site de suporte da NetApp ).



== 9.16.1 P2 (17 de abril de 2025)

O patch Cloud Volumes ONTAP 9.16.1 P2 já está disponível para atualização no Azure e no Google Cloud.  No entanto, esta versão não está disponível para atualização na AWS. O BlueXP solicitará que você atualize seus sistemas existentes para esta versão do patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P2["Veja a lista de bugs corrigidos no patch P2"^] (É necessário fazer login no site de suporte da NetApp ).



== 9.16.1 P1 (17 de abril de 2025)

O patch Cloud Volumes ONTAP 9.16.1 P1 já está disponível para atualização no Azure e no Google Cloud.  No entanto, esta versão não está disponível para atualização na AWS. O BlueXP solicitará que você atualize seus sistemas existentes para esta versão do patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P1["Veja a lista de bugs corrigidos no patch P1"^] (É necessário fazer login no site de suporte da NetApp ).



== 9.16.1 GA (06 de março de 2025)

Agora você pode usar a versão de Disponibilidade Geral do Cloud Volumes ONTAP 9.16.1 para implantação e atualização no Azure e no Google Cloud. No entanto, esta versão não está disponível para implantação e atualização na AWS.



== Notas de atualização

Leia estas notas para saber mais sobre como atualizar para esta versão.



=== Como atualizar

As atualizações do Cloud Volumes ONTAP devem ser concluídas no BlueXP.  Você não deve atualizar o Cloud Volumes ONTAP usando o System Manager ou a CLI.  Isso pode afetar a estabilidade do sistema.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Aprenda como fazer upgrade quando o BlueXP notificar você"^] .



=== Caminho de atualização suportado

Você pode atualizar para o Cloud Volumes ONTAP 9.16.1 GA a partir da versão 9.15.1 no Azure e no Google Cloud. O BlueXP solicitará que você atualize os sistemas Cloud Volumes ONTAP qualificados para esta versão.


NOTE: Para a AWS, você não será solicitado a fazer essa atualização. A atualização para o Cloud Volumes ONTAP 9.16.1 GA não é suportada na AWS.



=== Tempo de inatividade

* A atualização de um sistema de nó único deixa o sistema offline por até 25 minutos, durante os quais a E/S é interrompida.
* A atualização de um par de HA não causa interrupções e a E/S não é interrompida.  Durante esse processo de atualização não disruptivo, cada nó é atualizado em conjunto para continuar fornecendo E/S aos clientes.

