---
sidebar: sidebar 
permalink: reference-limitations-aws.html 
keywords: limitations, aws, amazon web services, flashe cache, alarms, cloudwatch, giveback, govcloud, c2s, aws outpost, outposts 
summary: Essas limitações conhecidas são específicas do Cloud Volumes ONTAP no Amazon Web Services. 
---
= Limitações conhecidas do Cloud Volumes ONTAP na AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As seguintes limitações conhecidas são específicas do Cloud Volumes ONTAP no Amazon Web Services.  Não deixe de revisar tambémlink:reference-limitations.html["Limitações para Cloud Volumes ONTAP em todos os provedores de nuvem"] .



== Limitações do AWS Outpost

Se você tiver um AWS Outpost, poderá implantar o Cloud Volumes ONTAP nesse Outpost selecionando a VPC do Outpost no assistente do ambiente de trabalho.  A experiência é a mesma de qualquer outra VPC que reside na AWS.  Observe que você precisará primeiro implantar um conector no seu AWS Outpost.

Há algumas limitações a serem apontadas:

* Somente sistemas Cloud Volumes ONTAP de nó único são suportados no momento
* As instâncias do EC2 que você pode usar com o Cloud Volumes ONTAP são limitadas ao que está disponível no seu Outpost
* Somente SSDs de uso geral (gp2) são suportados no momento




== Limitações do Flash Cache

Os tipos de instância C5D e R5D incluem armazenamento NVMe local, que o Cloud Volumes ONTAP usa como _Flash Cache_.  Observe as seguintes limitações:

* A compactação deve ser desabilitada em todos os volumes para aproveitar as melhorias de desempenho do Flash Cache até o Cloud Volumes ONTAP 9.12.0.  Ao implantar ou atualizar para o Cloud Volumes ONTAP 9.12.1, não é necessário desabilitar a compactação.
+
Você pode escolher nenhuma eficiência de armazenamento ao criar um volume do BlueXP ou pode criar um volume e então http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["desabilitar a compactação de dados usando a CLI"^] .

* O reaquecimento do cache após uma reinicialização não é suportado com o Cloud Volumes ONTAP.




== Alarmes falsos relatados pelo Amazon CloudWatch

O Cloud Volumes ONTAP não libera CPUs quando ocioso, portanto https://aws.amazon.com/cloudwatch/["Amazon CloudWatch"^] pode relatar um aviso de CPU alta para a instância EC2 porque ela vê 100% de uso.  Você pode ignorar este alarme.  O comando de estatísticas ONTAP exibe o uso real das CPUs.



== Os pares de alta disponibilidade do Cloud Volumes ONTAP não oferecem suporte imediato ao retorno do armazenamento

Após a reinicialização de um nó, o parceiro deve sincronizar os dados antes de poder retornar o armazenamento.  O tempo que leva para ressincronizar dados depende da quantidade de dados gravados pelos clientes enquanto o nó estava inativo e da velocidade de gravação de dados durante o período de devolução.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha.html["Aprenda como o armazenamento funciona em um par de Cloud Volumes ONTAP HA em execução na AWS"^] .
