---
sidebar: sidebar 
permalink: reference-limitations-gcp.html 
keywords: limitations, google cloud platform, gcp, psc, private service connect 
summary: Limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportados por esta versão do produto ou que não interoperam corretamente com ele. Revise essas limitações cuidadosamente. 
---
= Limitações conhecidas do Cloud Volumes ONTAP no Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As seguintes limitações conhecidas são específicas do Cloud Volumes ONTAP no Google Cloud Platform.  Não deixe de revisar tambémlink:reference-limitations.html["Limitações para Cloud Volumes ONTAP em todos os provedores de nuvem"] .



== Limitação com espelhamento de pacotes

https://cloud.google.com/vpc/docs/packet-mirroring["Espelhamento de pacotes"^]deve ser desabilitado no Google Cloud VPC no qual você implanta o Cloud Volumes ONTAP.

O Cloud Volumes ONTAP não pode operar corretamente se o espelhamento de pacotes estiver ativado.



== Limitações do Google Private Service Connect

Se você alavancar https://cloud.google.com/vpc/docs/private-service-connect["Conexão de serviço privado do Google"^] dentro da VPC na qual você está implantando o Cloud Volumes ONTAP , você precisará implementar registros DNS que encaminham o tráfego para o necessário https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["Pontos de extremidade da API BlueXP"^] .

Atualmente, o armazenamento em camadas de dados do Cloud Volumes ONTAP em um bucket do Google Cloud Storage não é suportado pelo Private Service Connect.
