---
sidebar: sidebar 
permalink: reference-limits-azure.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, page blobs, ebs, managed disks 
summary: O Cloud Volumes ONTAP tem limites de configuração de armazenamento no Azure para fornecer operações confiáveis.  Para melhor desempenho, não configure seu sistema nos valores máximos. 
---
= Limites de armazenamento para Cloud Volumes ONTAP no Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Cloud Volumes ONTAP tem limites de configuração de armazenamento para fornecer operações confiáveis.  Para melhor desempenho, não configure seu sistema nos valores máximos.



== Capacidade máxima do sistema por licença

A capacidade máxima do sistema para um sistema Cloud Volumes ONTAP é determinada por sua licença. A capacidade máxima do sistema inclui armazenamento baseado em disco, além de armazenamento de objetos usado para armazenamento de dados em camadas.

A NetApp não oferece suporte para exceder o limite de capacidade do sistema. Se você atingir o limite de capacidade licenciada, o BlueXP exibirá uma mensagem de ação necessária e impedirá que você adicione mais discos.

.Limite de capacidade para licenças baseadas em capacidade
Com o licenciamento baseado em capacidade, cada sistema Cloud Volumes ONTAP oferece suporte à hierarquização para armazenamento de objetos. A capacidade total em camadas pode ser ampliada até o limite de bucket do provedor de nuvem. Embora a licença não imponha restrições de capacidade, você deve seguir as https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Melhores práticas do FabricPool"^] para garantir desempenho ideal, confiabilidade e eficiência de custos ao configurar e gerenciar camadas. Consulte o https://learn.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account["Documentação do Azure para discos gerenciados"^] e https://learn.microsoft.com/en-us/azure/storage/blobs/scalability-targets["Documentação do Azure para armazenamento de blobs"^] .

Limites de capacidade para outros tipos de licença::


[cols="25,75"]
|===
| Licença | Capacidade máxima do sistema (discos + armazenamento de objetos) 


| Freemium | 500 GiB 


| PAYGO Explore | 2 TiB (a hierarquização de dados não é compatível com o Explore) 


| Padrão PAYGO | 10 TiB 


| PAYGO Premium | 368 TiB 


| Licença baseada em nó | 2 PiB (requer múltiplas licenças) 
|===
.Para HA, o limite de capacidade da licença é por nó ou para todo o par HA?
O limite de capacidade é para todo o par HA. Não é por nó. Por exemplo, se você usar a licença Premium, poderá ter até 368 TiB de capacidade entre os dois nós.



== Limites agregados

O Cloud Volumes ONTAP usa o armazenamento do Azure como discos e os agrupa em _agregados_.  Agregados fornecem armazenamento para volumes.

[cols="2*"]
|===
| Parâmetro | Limite 


| Número máximo de agregados | Igual ao limite do disco 


| Tamanho máximo agregado ^1^ | 384 TiB de capacidade bruta para nó único ^2^ 352 TiB de capacidade bruta para nó único com PAYGO 96 TiB de capacidade bruta para pares HA com blob de página 384 TiB de capacidade bruta para pares HA com discos gerenciados 


| Discos por agregado | 1-12 ^3^ 


| Número máximo de grupos RAID por agregado | 1 
|===
Observações:

. O limite de capacidade agregada é baseado nos discos que compõem o agregado.  O limite não inclui o armazenamento de objetos usado para hierarquização de dados.
. Se estiver usando o licenciamento baseado em nó, duas licenças BYOL serão necessárias para atingir 384 TiB.
. Todos os discos em um agregado devem ter o mesmo tamanho.




== Limites de disco e camadas por tamanho de VM

Os limites de capacidade variam de acordo com o tamanho da VM e o tipo de sistema (nó único ou par HA).

As notas abaixo explicam os números nas tabelas:

* Os limites do disco são específicos para discos que contêm dados do usuário.
+
Os limites não incluem o disco raiz, o disco principal e a VNVRAM.

* Você pode ver a capacidade máxima do sistema quando usa apenas discos e quando usa discos e camadas de dados frios para armazenamento de objetos.
* Sistemas de nó único e HA que usam discos gerenciados têm no máximo 32 TiB por disco.  O número de discos suportados varia de acordo com o tamanho da VM.
* Os sistemas HA que usam blobs de página têm no máximo 8 TiB por blob de página.  O número de discos suportados varia de acordo com o tamanho da VM.
* O limite de 896 TiB baseado em disco listado para sistemas de nó único com determinados tamanhos de VM é o limite _testado_.




=== Limites para diferentes modos de implantação de licenciamento baseado em capacidade

Os seguintes limites de disco se aplicam aos sistemas Cloud Volumes ONTAP que usam um pacote de licenciamento baseado em capacidade. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Saiba mais sobre as opções de licenciamento do Cloud Volumes ONTAP"^] .


NOTE: Para obter a capacidade máxima do sistema e os limites de capacidade de camadas de dados para um único nó, pares de HA em uma única zona de disponibilidade com blobs de página e pares de HA em uma única e várias zonas de disponibilidade com discos gerenciados compartilhados, consulte<<cap-license-azure>> .



==== Nó único

[cols="14,20,31"]
|===
| Tamanho da VM | Máximo de discos de dados por nó | Capacidade máxima do sistema apenas com discos 


| DS4_v2 | 29 | 896 TiB 


| DS5_v2 | 61 | 896 TiB 


| DS13_v2 | 29 | 896 TiB 


| DS14_v2 | 61 | 896 TiB 


| DS15_v2 | 61 | 896 TiB 


| E4s_v3 | 5 | 160 TiB 


| E8s_v3 | 13 | 416 TiB 


| E32s_v3 | 29 | 896 TiB 


| E48s_v3 | 29 | 896 TiB 


| E64is_v3 | 29 | 896 TiB 


| E4ds_v4 | 5 | 160 TiB 


| E8ds_v4 | 13 | 416 TiB 


| E32ds_v4 | 29 | 896 TiB 


| E48ds_v4 | 29 | 896 TiB 


| E80ids_v4 | 61 | 896 TiB 


| E4ds_v5 | 5 | 160 TiB 


| E8ds_v5 | 13 | 416 TiB 


| E20ds_v5 | 29 | 896 TiB 


| E32ds_v5 | 29 | 896 TiB 


| E48ds_v5 | 29 | 896 TiB 


| E64ds_v5 | 29 | 896 TiB 


| L8s_v3 | 12 | 384 TiB 


| L16s_v3 | 28 | 896 TiB 


| L32s_v3 | 28 | 896 TiB 


| L48s_v3 | 28 | 896 TiB 


| L64s_v3 | 28 | 896 TiB 
|===


==== Pares de HA em uma única zona de disponibilidade com blobs de página

[cols="14,20,31"]
|===
| Tamanho da VM | Máximo de discos de dados para um par HA | Capacidade máxima do sistema apenas com discos 


| DS4_v2 | 29 | 232 TiB 


| DS5_v2 | 61 | 488 TiB 


| DS13_v2 | 29 | 232 TiB 


| DS14_v2 | 61 | 488 TiB 


| DS15_v2 | 61 | 488 TiB 


| E8s_v3 | 13 | 104 TiB 


| E48s_v3 | 29 | 232 TiB 


| E8ds_v4 | 13 | 104 TiB 


| E32ds_v4 | 29 | 232 TiB 


| E48ds_v4 | 29 | 232 TiB 


| E80ids_v4 | 61 | 488 TiB 
|===


==== Pares de HA em uma única zona de disponibilidade com discos gerenciados compartilhados

[cols="14,20,31"]
|===
| Tamanho da VM | Máximo de discos de dados para um par HA | Capacidade máxima do sistema apenas com discos 


| E8ds_v4 | 12 | 384 TiB 


| E32ds_v4 | 28 | 896 TiB 


| E48ds_v4 | 28 | 896 TiB 


| E80ids_v4 | 28 | 896 TiB 


| E8ds_v5 | 12 | 384 TiB 


| E20ds_v5 | 28 | 896 TiB 


| E32ds_v5 | 28 | 896 TiB 


| E48ds_v5 | 28 | 896 TiB 


| E64ds_v5 | 28 | 896 TiB 


| L16s_v3 | 28 | 896 TiB 


| L32s_v3 | 28 | 896 TiB 


| L48s_v3 | 28 | 896 TiB 


| L64s_v3 | 28 | 896 TiB 
|===


==== Pares de HA em várias zonas de disponibilidade com discos gerenciados compartilhados

[cols="14,20,31"]
|===
| Tamanho da VM | Máximo de discos de dados para um par HA | Capacidade máxima do sistema apenas com discos 


| E8ds_v4 | 12 | 384 TiB 


| E32ds_v4 | 28 | 896 TiB 


| E48ds_v4 | 28 | 896 TiB 


| E80ids_v4 | 28 | 896 TiB 


| E8ds_v5 | 12 | 384 TiB 


| E20ds_v5 | 28 | 896 TiB 


| E32ds_v5 | 28 | 896 TiB 


| E48ds_v5 | 28 | 896 TiB 


| E64ds_v5 | 28 | 896 TiB 


| L16s_v3 | 28 | 896 TiB 


| L32s_v3 | 28 | 896 TiB 


| L48s_v3 | 28 | 896 TiB 


| L64s_v3 | 28 | 896 TiB 
|===


=== Limites para diferentes modos de implantação de licenciamento baseado em nó

Os seguintes limites de disco se aplicam aos sistemas Cloud Volumes ONTAP que usam licenciamento baseado em nó. O licenciamento baseado em nó é o modelo da geração anterior que permite licenciar o Cloud Volumes ONTAP por nó. O licenciamento baseado em nós ainda está disponível para clientes existentes.

Você pode comprar várias licenças baseadas em nós para um sistema de nó único ou par de HA do Cloud Volumes ONTAP BYOL para alocar mais de 368 TiB de capacidade, até o limite máximo de capacidade do sistema testado e suportado de 2 PiB. Esteja ciente de que os limites do disco podem impedir que você atinja o limite de capacidade usando apenas discos. Você pode ir além do limite do disco por https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["hierarquização de dados inativos para armazenamento de objetos"^] . https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Aprenda como adicionar licenças de sistema adicionais ao Cloud Volumes ONTAP"^] . O Cloud Volumes ONTAP suporta até a capacidade máxima do sistema testada e suportada de 2 PiB, e ultrapassar o limite de 2 PiB resulta em uma configuração de sistema não suportada.



==== Nó único

O nó único tem duas opções de licenciamento baseadas em nó: PAYGO Premium e BYOL.

.Nó único com PAYGO Premium
[%collapsible]
====
[cols="14,20,31,33"]
|===
| Tamanho da VM | Máximo de discos de dados por nó | Capacidade máxima do sistema apenas com discos | Capacidade máxima do sistema com discos e camadas de dados 


| DS5_v2 | 61 | 368 TiB | 368 TiB 


| DS14_v2 | 61 | 368 TiB | 368 TiB 


| DS15_v2 | 61 | 368 TiB | 368 TiB 


| E32s_v3 | 29 | 368 TiB | 368 TiB 


| E48s_v3 | 29 | 368 TiB | 368 TiB 


| E64is_v3 | 29 | 368 TiB | 368 TiB 


| E32ds_v4 | 29 | 368 TiB | 368 TiB 


| E48ds_v4 | 29 | 368 TiB | 368 TiB 


| E80ids_v4 | 61 | 368 TiB | 368 TiB 


| E20ds_v5 | 29 | 896 TiB | 2 PiB 


| E32ds_v5 | 29 | 896 TiB | 2 PiB 


| E48ds_v5 | 29 | 896 TiB | 2 PiB 


| E64ds_v5 | 29 | 896 TiB | 2 PiB 
|===
====
.Nó único com BYOL
[%collapsible]
====
[cols="10,18,18,18,18,18"]
|===
| Tamanho da VM | Máximo de discos de dados por nó 2+| Capacidade máxima do sistema com uma licença 2+| Capacidade máxima do sistema com múltiplas licenças 


2+|  | *Discos sozinhos* | *Discos + níveis de dados* | *Discos sozinhos* | *Discos + níveis de dados* 


| DS4_v2 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| DS5_v2 | 61 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| DS13_v2 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| DS14_v2 | 61 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| DS15_v2 | 61 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| L8s_v2 | 13 | 368 TiB | 368 TiB | 416 TiB | 2 PiB 


| E4s_v3 | 5 | 160 TiB | 368 TiB | 160 TiB | 2 PiB 


| E8s_v3 | 13 | 368 TiB | 368 TiB | 416 TiB | 2 PiB 


| E32s_v3 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E48s_v3 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E64is_v3 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E4ds_v4 | 5 | 160 TiB | 368 TiB | 160 TiB | 2 PiB 


| E8ds_v4 | 13 | 368 TiB | 368 TiB | 416 TiB | 2 PiB 


| E32ds_v4 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E48ds_v4 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E80ids_v4 | 61 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E4ds_v5 | 5 | 160 TiB | 368 TiB | 160 TiB | 2 PiB 


| E8ds_v5 | 13 | 368 TiB | 368 TiB | 416 TiB | 2 PiB 


| E20ds_v5 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E32ds_v5 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E48ds_v5 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E64ds_v5 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 
|===
====


==== Pares HA

Os pares de HA têm dois tipos de configuração: blob de página e zona de disponibilidade múltipla.  Cada configuração tem duas opções de licenciamento baseadas em nós: PAYGO Premium e BYOL.

.PAYGO Premium: pares HA em zona de disponibilidade única com blobs de página
[%collapsible]
====
[cols="14,20,31,33"]
|===
| Tamanho da VM | Máximo de discos de dados para um par HA | Capacidade máxima do sistema apenas com discos | Capacidade máxima do sistema com discos e camadas de dados 


| DS5_v2 | 61 | 368 TiB | 368 TiB 


| DS14_v2 | 61 | 368 TiB | 368 TiB 


| DS15_v2 | 61 | 368 TiB | 368 TiB 


| E8s_v3 | 13 | 104 TiB | 368 TiB 


| E48s_v3 | 29 | 232 TiB | 368 TiB 


| E32ds_v4 | 29 | 232 TiB | 368 TiB 


| E48ds_v4 | 29 | 232 TiB | 368 TiB 


| E80ids_v4 | 61 | 368 TiB | 368 TiB 
|===
====
.PAYGO Premium: pares de alta disponibilidade em uma configuração de zona de disponibilidade múltipla com discos gerenciados compartilhados
[%collapsible]
====
[cols="14,20,31,33"]
|===
| Tamanho da VM | Máximo de discos de dados para um par HA | Capacidade máxima do sistema apenas com discos | Capacidade máxima do sistema com discos e camadas de dados 


| E32ds_v4 | 28 | 368 TiB | 368 TiB 


| E48ds_v4 | 28 | 368 TiB | 368 TiB 


| E80ids_v4 | 28 | 368 TiB | 368 TiB 


| E20ds_v5 | 28 | 896 TiB | 2 PiB 


| E32ds_v5 | 28 | 896 TiB | 2 PiB 


| E48ds_v5 | 28 | 896 TiB | 2 PiB 


| E64ds_v5 | 28 | 896 TiB | 2 PiB 
|===
====
.BYOL: pares HA em zona de disponibilidade única com blobs de página
[%collapsible]
====
[cols="10,18,18,18,18,18"]
|===
| Tamanho da VM | Máximo de discos de dados para um par HA 2+| Capacidade máxima do sistema com uma licença 2+| Capacidade máxima do sistema com múltiplas licenças 


2+|  | *Discos sozinhos* | *Discos + níveis de dados* | *Discos sozinhos* | *Discos + níveis de dados* 


| DS4_v2 | 29 | 232 TiB | 368 TiB | 232 TiB | 2 PiB 


| DS5_v2 | 61 | 368 TiB | 368 TiB | 488 TiB | 2 PiB 


| DS13_v2 | 29 | 232 TiB | 368 TiB | 232 TiB | 2 PiB 


| DS14_v2 | 61 | 368 TiB | 368 TiB | 488 TiB | 2 PiB 


| DS15_v2 | 61 | 368 TiB | 368 TiB | 488 TiB | 2 PiB 


| E8s_v3 | 13 | 104 TiB | 368 TiB | 104 TiB | 2 PiB 


| E48s_v3 | 29 | 232 TiB | 368 TiB | 232 TiB | 2 PiB 


| E8ds_v4 | 13 | 104 TiB | 368 TiB | 104 TiB | 2 PiB 


| E32ds_v4 | 29 | 232 TiB | 368 TiB | 232 TiB | 2 PiB 


| E48ds_v4 | 29 | 232 TiB | 368 TiB | 232 TiB | 2 PiB 


| E80ids_v4 | 61 | 368 TiB | 368 TiB | 488 TiB | 2 PiB 
|===
====
.BYOL: pares de HA em uma configuração de zona de disponibilidade múltipla com discos gerenciados compartilhados
[%collapsible]
====
[cols="10,18,18,18,18,18"]
|===
| Tamanho da VM | Máximo de discos de dados para um par HA 2+| Capacidade máxima do sistema com uma licença 2+| Capacidade máxima do sistema com múltiplas licenças 


2+|  | *Discos sozinhos* | *Discos + níveis de dados* | *Discos sozinhos* | *Discos + níveis de dados* 


| E8ds_v4 | 12 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 


| E32ds_v4 | 28 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 


| E48ds_v4 | 28 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 


| E80ids_v4 | 28 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 


| E8ds_v5 | 12 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 


| E20ds_v5 | 28 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 


| E32ds_v5 | 28 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 


| E48ds_v5 | 28 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 


| E64ds_v5 | 28 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 
|===
====


== Limites de VM de armazenamento

Algumas configurações permitem que você crie VMs de armazenamento adicionais (SVMs) para o Cloud Volumes ONTAP.

Estes são os limites testados. Não há suporte para configurar mais VMs de armazenamento.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html["Aprenda a criar VMs de armazenamento adicionais"^] .

[cols="2*"]
|===
| Tipo de licença | Limite de VM de armazenamento 


| *Freemium*  a| 
24 VMs de armazenamento no total ^1,2^



| *PAYGO ou BYOL baseado em capacidade* ^3^  a| 
24 VMs de armazenamento no total ^1,2^



| *BYOL baseado em nó* ^4^  a| 
24 VMs de armazenamento no total ^1,2^



| *PAYGO baseado em nó*  a| 
* 1 VM de armazenamento para servir dados
* 1 VM de armazenamento para recuperação de desastres


|===
. Essas 24 VMs de armazenamento podem fornecer dados ou ser configuradas para recuperação de desastres (DR).
. Cada VM de armazenamento pode ter até três LIFs, onde dois são LIFs de dados e um é um LIF de gerenciamento de SVM.
. Para licenciamento baseado em capacidade, não há custos extras de licenciamento para VMs de armazenamento adicionais, mas há uma cobrança de capacidade mínima de 4 TiB por VM de armazenamento.  Por exemplo, se você criar duas VMs de armazenamento e cada uma tiver 2 TiB de capacidade provisionada, você será cobrado um total de 8 TiB.
. Para BYOL baseado em nó, uma licença complementar é necessária para cada VM de armazenamento de _servidor de dados_ adicional além da primeira VM de armazenamento que vem com o Cloud Volumes ONTAP por padrão. Entre em contato com sua equipe de contas para obter uma licença complementar de VM de armazenamento.
+
VMs de armazenamento para recuperação de desastres (DR) não precisam de uma licença complementar, mas contam para o limite de VMs de armazenamento. Por exemplo, se você tiver 12 VMs de serviço de dados e 12 VMs de armazenamento de DR, você atingiu o limite e não poderá criar mais.





== Limites de arquivo e volume

[cols="22,22,56"]
|===
| Armazenamento lógico | Parâmetro | Limite 


.2+| *Arquivos* | Tamanho máximo ^2^ | 128 TB 


| Máximo por volume | Depende do tamanho do volume, até 2 bilhões 


| * Volumes FlexClone * | Profundidade hierárquica do clone ^1^ | 499 


.3+| * Volumes FlexVol * | Máximo por nó | 500 


| Tamanho mínimo | 20 MB 


| Tamanho máximo ^3^ | 300 TiB 


| *Qárvores* | FlexVol volume | 4.995 


| *Cópias instantâneas* | FlexVol volume | 1.023 
|===
. A profundidade do clone hierárquico é a profundidade máxima de uma hierarquia aninhada de volumes FlexClone que pode ser criada a partir de um único FlexVol volume.
. A partir do ONTAP 9.12.1P2, o limite é 128 TB.  No ONTAP 9.11.1 e versões anteriores, o limite é 16 TB.
. A criação de FlexVol volume até o tamanho máximo de 300 TiB é suportada usando as seguintes ferramentas e versões mínimas:
+
** Gerenciador de sistemas e ONTAP CLI a partir do Cloud Volumes ONTAP 9.12.1 P2 e 9.13.0 P2
** BlueXP a partir do Cloud Volumes ONTAP 9.13.1






== Limites de armazenamento iSCSI

[cols="3*"]
|===
| Armazenamento iSCSI | Parâmetro | Limite 


.4+| *LUNs* | Máximo por nó | 1.024 


| Número máximo de mapas LUN | 1.024 


| Tamanho máximo | 16 TiB 


| Máximo por volume | 512 


| *igrupos* | Máximo por nó | 256 


.2+| *Iniciadores* | Máximo por nó | 512 


| Máximo por igroup | 128 


| *Sessões iSCSI* | Máximo por nó | 1.024 


.2+| *LIFs* | Máximo por porta | 32 


| Máximo por conjunto de portas | 32 


| *Conjuntos de portas* | Máximo por nó | 256 
|===