---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: O Cloud Volumes ONTAP tem limites de configuração de armazenamento no Google Cloud para fornecer operações confiáveis.  Para melhor desempenho, não configure seu sistema nos valores máximos. 
---
= Limites de armazenamento para Cloud Volumes ONTAP no Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Cloud Volumes ONTAP tem limites de configuração de armazenamento para fornecer operações confiáveis.  Para melhor desempenho, não configure seu sistema nos valores máximos.



== Capacidade máxima do sistema por licença

A capacidade máxima do sistema para um sistema Cloud Volumes ONTAP é determinada por sua licença. A capacidade máxima do sistema inclui armazenamento baseado em disco, além de armazenamento de objetos usado para armazenamento de dados em camadas.

A NetApp não oferece suporte para exceder o limite de capacidade do sistema. Se você atingir o limite de capacidade licenciada, o BlueXP exibirá uma mensagem de ação necessária e não permitirá mais que você adicione discos adicionais.

Para algumas configurações, os limites de disco impedem que você atinja o limite de capacidade usando apenas discos.  Você pode atingir o limite de capacidade por https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["hierarquização de dados inativos para armazenamento de objetos"^] .  Consulte os limites do disco abaixo para obter mais detalhes.

.Limite de capacidade para licenças baseadas em capacidade
Com o licenciamento baseado em capacidade, cada sistema Cloud Volumes ONTAP oferece suporte à hierarquização para armazenamento de objetos. A capacidade total em camadas pode ser ampliada até o limite de bucket do provedor de nuvem. Embora a licença não imponha restrições de capacidade, você deve seguir as https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Melhores práticas do FabricPool"^] para garantir desempenho ideal, confiabilidade e eficiência de custos ao configurar e gerenciar camadas. Consulte o  https://cloud.google.com/storage/docs/buckets["Documentação do Google Cloud"^] para maiores informações.

Limites de capacidade para outros tipos de licença::


[cols="25,75"]
|===
| Licença | Capacidade máxima do sistema (discos + armazenamento de objetos) 


| Freemium | 500 GB 


| PAYGO Explore | 2 TB (a hierarquização de dados não é compatível com o Explore) 


| Padrão PAYGO | 10 TB 


| PAYGO Premium | 368 TB 


| Licença baseada em nó | 2 PiB (requer múltiplas licenças) 
|===
.Para um par HA, o limite de capacidade licenciada é por nó ou para todo o par HA?
O limite de capacidade é para todo o par HA. Não é por nó. Por exemplo, se você usar a licença Premium, poderá ter até 368 TB de capacidade entre os dois nós.

.Para um par HA, os dados espelhados são contabilizados no limite de capacidade licenciada?
Não, não é. Os dados em um par de HA são espelhados de forma sincronizada entre os nós para que os dados estejam disponíveis em caso de falha no Google Cloud. Por exemplo, se você comprar um disco de 8 TB no nó A, o BlueXP também alocará um disco de 8 TB no nó B que será usado para dados espelhados. Embora 16 TB de capacidade sejam configurados, apenas 8 TB são contabilizados no limite da licença.



== Limites agregados

O Cloud Volumes ONTAP agrupa discos do Google Cloud Platform em _agregados_.  Agregados fornecem armazenamento para volumes.

[cols="2*"]
|===
| Parâmetro | Limite 


| Número máximo de agregados de dados ^1^  a| 
* 99 para nó único
* 64 para um par HA inteiro




| Tamanho máximo agregado | 256 TB de capacidade bruta ^2^ 


| Discos por agregado | 1-6 ^3^ 


| Número máximo de grupos RAID por agregado | 1 
|===
Observações:

. O número máximo de agregados de dados não inclui o agregado raiz.
. Os discos que compõem o agregado determinam o limite de capacidade do agregado. Este limite não inclui o armazenamento de objetos usado para hierarquização de dados.
. Todos os discos em um agregado devem ter o mesmo tamanho.




== Limites de disco e camadas

A tabela abaixo mostra a capacidade máxima do sistema com discos sozinhos e com discos e camadas de dados frios para armazenamento de objetos.  Os limites do disco são específicos para discos que contêm dados do usuário.  Os limites não incluem o disco de inicialização, o disco raiz ou a NVRAM.

[cols="60,40"]
|===
| Parâmetro | Limite 


| Discos de dados máximos  a| 
* 124 para sistemas de nó único
* 123 por nó para pares HA




| Tamanho máximo do disco | 64 TB 


| Capacidade máxima do sistema apenas com discos | 256 TB ^1^ 


| Capacidade máxima do sistema com discos e armazenamento em camadas de dados frios em um bucket do Google Cloud Storage | Depende da licença.  Consulte os limites máximos de capacidade do sistema acima. 
|===
^1^ Este limite é definido pelos limites da máquina virtual no Google Cloud Platform.



== Limites de VM de armazenamento

Algumas configurações permitem que você crie VMs de armazenamento adicionais (SVMs) para o Cloud Volumes ONTAP.

Estes são os limites testados. Não há suporte para configurar mais VMs de armazenamento.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["Aprenda a criar VMs de armazenamento adicionais"^] .

[cols="2*"]
|===
| Tipo de licença | Limite de VM de armazenamento 


| *Freemium*  a| 
24 VMs de armazenamento no total ^1^



| *PAYGO ou BYOL baseado em capacidade* ^2^  a| 
24 VMs de armazenamento no total ^1^



| *BYOL baseado em nó* ^3^  a| 
24 VMs de armazenamento no total ^1^



| *PAYGO baseado em nó*  a| 
* 1 VM de armazenamento para servir dados
* 1 VM de armazenamento para recuperação de desastres


|===
. Essas 24 VMs de armazenamento podem fornecer dados ou ser configuradas para recuperação de desastres (DR).
. Para licenciamento baseado em capacidade, não há custos extras de licenciamento para VMs de armazenamento adicionais, mas há uma cobrança de capacidade mínima de 4 TiB por VM de armazenamento.  Por exemplo, se você criar duas VMs de armazenamento e cada uma tiver 2 TiB de capacidade provisionada, você será cobrado um total de 8 TiB.
. Para BYOL baseado em nó, uma licença complementar é necessária para cada VM de armazenamento de _servidor de dados_ adicional além da primeira VM de armazenamento que vem com o Cloud Volumes ONTAP por padrão. Entre em contato com sua equipe de contas para obter uma licença complementar de VM de armazenamento.
+
As VMs de armazenamento que você configura para recuperação de desastres (DR) não exigem uma licença complementar (elas são gratuitas), mas são contabilizadas no limite de VMs de armazenamento.  Por exemplo, se você tiver 12 VMs de armazenamento de serviço de dados e 12 VMs de armazenamento configuradas para recuperação de desastres, você atingiu o limite e não poderá criar nenhuma VM de armazenamento adicional.





== Limites lógicos de armazenamento

[cols="22,22,56"]
|===
| Armazenamento lógico | Parâmetro | Limite 


.2+| *Arquivos* | Tamanho máximo ^2^ | 128 TB 


| Máximo por volume | Depende do tamanho do volume, até 2 bilhões 


| * Volumes FlexClone * | Profundidade hierárquica do clone ^12^ | 499 


.3+| * Volumes FlexVol * | Máximo por nó | 500 


| Tamanho mínimo | 20 MB 


| Tamanho máximo ^3^ | 300 TiB 


| *Qárvores* | FlexVol volume | 4.995 


| *Cópias instantâneas* | FlexVol volume | 1.023 
|===
. A profundidade do clone hierárquico é a profundidade máxima de uma hierarquia aninhada de volumes FlexClone que pode ser criada a partir de um único FlexVol volume.
. A partir do ONTAP 9.12.1P2, o limite é 128 TB.  No ONTAP 9.11.1 e versões anteriores, o limite é 16 TB.
. A criação de FlexVol volume até o tamanho máximo de 300 TiB é suportada usando as seguintes ferramentas e versões mínimas:
+
** Gerenciador de sistemas e ONTAP CLI a partir do Cloud Volumes ONTAP 9.12.1 P2 e 9.13.0 P2
** BlueXP a partir do Cloud Volumes ONTAP 9.13.1






== Limites de armazenamento iSCSI

[cols="3*"]
|===
| Armazenamento iSCSI | Parâmetro | Limite 


.4+| *LUNs* | Máximo por nó | 1.024 


| Número máximo de mapas LUN | 1.024 


| Tamanho máximo | 16 TB 


| Máximo por volume | 512 


| *igrupos* | Máximo por nó | 256 


.2+| *Iniciadores* | Máximo por nó | 512 


| Máximo por igroup | 128 


| *Sessões iSCSI* | Máximo por nó | 1.024 


.2+| *LIFs* | Máximo por porta | 1 


| Máximo por conjunto de portas | 32 


| *Conjuntos de portas* | Máximo por nó | 256 
|===


== Os pares de alta disponibilidade do Cloud Volumes ONTAP não oferecem suporte imediato ao retorno do armazenamento

Após a reinicialização de um nó, o parceiro deve sincronizar os dados antes de poder retornar o armazenamento.  O tempo que leva para ressincronizar dados depende da quantidade de dados gravados pelos clientes enquanto o nó estava inativo e da velocidade de gravação de dados durante o período de devolução.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-google-cloud.html["Aprenda como o armazenamento funciona em um par de Cloud Volumes ONTAP HA em execução no Google Cloud"^] .
